import type { ProductIconId } from "./productIcons";

// Whole-name alternatives; canonical display names are added by the registry.
export const PRODUCT_ICON_ALIASES: ReadonlyArray<readonly [string, ProductIconId]> = [
  ["adobe creative cloud", "creative-cloud"],
  ["microsoft sharepoint", "sharepoint"],
  ["amazon web services", "aws"],
  ["microsoft exchange", "exchange"],
  ["microsoft onedrive", "onedrive"],
  ["adobe illustrator", "illustrator"],
  ["microsoft outlook", "outlook"],
  ["google workspace", "google"],
  ["microsoft office", "microsoft-365"],
  ["adobe photoshop", "photoshop"],
  ["microsoft azure", "azure"],
  ["microsoft teams", "teams"],
  ["acrobat reader", "adobe-acrobat"],
  ["creative cloud", "creative-cloud"],
  ["adobe acrobat", "adobe-acrobat"],
  ["google sheets", "google-sheets"],
  ["microsoft 365", "microsoft-365"],
  ["google cloud", "google-cloud"],
  ["google drive", "google-drive"],
  ["malwarebytes", "malwarebytes"],
  ["sentinel one", "sentinelone"],
  ["sentinelone", "sentinelone"],
  ["sentinalone", "sentinelone"],
  ["סנטינל וואן", "sentinelone"],
  ["סנטינלוואן", "sentinelone"],
  ["migrationwiz", "bittitan"],
  ["migration wiz", "bittitan"],
  ["ביט טיטאן", "bittitan"],
  ["microsoft365", "microsoft-365"],
  ["bitdefender", "bitdefender"],
  ["google docs", "google-docs"],
  ["google meet", "google-meet"],
  ["illustrator", "illustrator"],
  ["cloudflare", "cloudflare"],
  ["confluence", "confluence"],
  ["office 365", "microsoft-365"],
  ["salesforce", "salesforce"],
  ["sharepoint", "sharepoint"],
  ["teamviewer", "teamviewer"],
  ["1password", "1password"],
  ["atlassian", "atlassian"],
  ["sentinel1", "sentinelone"],
  ["bit titan", "bittitan"],
  ["bittitan", "bittitan"],
  ["ביטטיטאן", "bittitan"],
  ["ביטטיטן", "bittitan"],
  ["fortigate", "fortinet"],
  ["microsoft", "microsoft"],
  ["office365", "microsoft-365"],
  ["one drive", "onedrive"],
  ["photoshop", "photoshop"],
  ["autodesk", "autodesk"],
  ["docusign", "docusign"],
  ["exchange", "exchange"],
  ["fortinet", "fortinet"],
  ["onedrive", "onedrive"],
  ["power bi", "power-bi"],
  ["acrobat", "adobe-acrobat"],
  ["acronis", "acronis"],
  ["acronix", "acronis"],
  ["autocad", "autodesk"],
  ["dropbox", "dropbox"],
  ["g suite", "google"],
  ["hubspot", "hubspot"],
  ["outlook", "outlook"],
  ["vsphere", "vmware"],
  ["windows", "microsoft"],
  ["docker", "docker"],
  ["github", "github"],
  ["gitlab", "gitlab"],
  ["google", "google"],
  ["gsuite", "google"],
  ["notion", "notion"],
  ["trello", "trello"],
  ["vmware", "vmware"],
  ["adobe", "adobe"],
  ["asana", "asana"],
  ["azure", "azure"],
  ["canva", "canva"],
  ["cisco", "cisco"],
  ["figma", "figma"],
  ["gmail", "gmail"],
  ["slack", "slack"],
  ["teams", "teams"],
  ["veeam", "veeam"],
  ["webex", "webex"],
  ["jira", "jira"],
  ["m365", "microsoft-365"],
  ["o365", "microsoft-365"],
  ["okta", "okta"],
  ["zoom", "zoom"],
  ["365", "microsoft-365"],
  ["aws", "aws"],
  ["gcp", "google-cloud"],
  ["trendmicro", "trend-micro"],
  ["טרנד מיקרו", "trend-micro"],
  ["palo alto", "palo-alto"],
  ["paloalto", "palo-alto"],
  ["פאלו אלטו", "palo-alto"],
  ["ביטוורדן", "bitwarden"],
  ["דאטו", "datto"],
  ["בקבלייז", "backblaze"],
  ["וסאבי", "wasabi"],
  ["any desk", "anydesk"],
  ["אנידסק", "anydesk"],
  ["proxmox ve", "proxmox"],
  ["פרוקסמוקס", "proxmox"],
  ["נוטניקס", "nutanix"],
  ["diskstation", "synology"],
  ["סינולוגי", "synology"],
  ["קיונאפ", "qnap"],
  ["unifi", "ubiquiti"],
  ["יוביקוויטי", "ubiquiti"],
  ["יוניפיי", "ubiquiti"],
  ["redhat", "red-hat"],
  ["rhel", "red-hat"],
  ["רד האט", "red-hat"],
  ["אובונטו", "ubuntu"],
  ["digital ocean", "digitalocean"],
  ["דיגיטל אושן", "digitalocean"],
  ["זוהו", "zoho"],
  ["intellij", "jetbrains"],
  ["pycharm", "jetbrains"],
  ["webstorm", "jetbrains"],
  ["גטבריינס", "jetbrains"],
  ["ג׳טבריינס", "jetbrains"],
  ["פוסטמן", "postman"],
  ["דטהדוג", "datadog"],
  ["דאטאדוג", "datadog"],
  ["סנטרי", "sentry"],
  ["אווסט", "avast"],
  ["אווירה", "avira"],
  ["nord vpn", "nordvpn"],
  ["נורד וי פי אן", "nordvpn"],
  ["open vpn", "openvpn"],
  ["אופן וי פי אן", "openvpn"],
  ["wire guard", "wireguard"],
  ["וויירגארד", "wireguard"],
  ["tail scale", "tailscale"],
  ["טיילסקייל", "tailscale"],
  ["סניק", "snyk"],
  ["ספלנק", "splunk"],
  ["newrelic", "new-relic"],
  ["ניו רליק", "new-relic"],
  ["גרפנה", "grafana"],
  ["nod32", "eset"],
  ["איסט", "eset"],
  ["איסט נוד32", "eset"],
  ["crowd strike", "crowdstrike"],
  ["falcon", "crowdstrike"],
  ["קראודסטרייק", "crowdstrike"],
  ["קראוד סטרייק", "crowdstrike"],
  ["checkpoint", "checkpoint"],
  ["צ׳ק פוינט", "checkpoint"],
  ["צק פוינט", "checkpoint"],
  ["צקפוינט", "checkpoint"],
  ["זיסקיילר", "zscaler"],
  ["זי סקיילר", "zscaler"],
  ["proof point", "proofpoint"],
  ["פרופפוינט", "proofpoint"],
  ["פרוף פוינט", "proofpoint"],
  ["cisco duo", "duo"],
  ["דואו", "duo"],
  ["keeper security", "keeper"],
  ["קיפר", "keeper"],
  ["share gate", "sharegate"],
  ["שיירגייט", "sharegate"],
  ["שייר גייט", "sharegate"],
  ["connect wise", "connectwise"],
  ["screenconnect", "connectwise"],
  ["קונקטווייז", "connectwise"],
  ["קונקט ווייז", "connectwise"],
  ["ג׳אמף", "jamf"],
  ["גאמף", "jamf"],
  ["watch guard", "watchguard"],
  ["firebox", "watchguard"],
  ["וואטשגארד", "watchguard"],
  ["ווטשגארד", "watchguard"],
  ["comm vault", "commvault"],
  ["קומוולט", "commvault"],
  ["קום וולט", "commvault"],
  ["msp 360", "msp360"],
  ["cloudberry", "msp360"],
  ["cloud berry", "msp360"],
  ["קלאודברי", "msp360"],
  ["fresh works", "freshworks"],
  ["freshdesk", "freshworks"],
  ["freshservice", "freshworks"],
  ["פרשוורקס", "freshworks"],
  ["פרש דסק", "freshworks"],
  ["פרש סרוויס", "freshworks"],
];
