import { expect, test, setEditMode } from "./fixtures";

test("applies saved billing prices by license identity while preserving overrides and deleted entries", async ({ page }) => {
  await page.goto("/");
  const catalog = page.getByRole("region", { name: "Licenses", exact: true });
  await expect(catalog.getByRole("combobox", { name: "Billing Option", exact: true })).toHaveCount(0);
  await page.getByLabel("Customer", { exact: true }).fill("Saved billing customer");
  await setEditMode(page, true);
  await page.getByRole("button", { name: "Edit Business Basic", exact: true }).click();
  const editor = page.getByRole("dialog", { name: "Edit license", exact: true });
  await editor.getByLabel("Monthly price", { exact: true }).fill("10");
  await editor.getByLabel("Annual paid monthly price", { exact: true }).fill("12");
  await editor.getByRole("button", { name: "Save changes", exact: true }).click();
  await setEditMode(page, false);
  await page.getByRole("button", { name: "Add Business Basic to quote", exact: true }).press("Enter");
  const line = page.getByRole("group", { name: "Business Basic", exact: true }).first();
  const price = line.getByRole("textbox", { name: "Price", exact: true });
  const billing = line.getByRole("combobox", { name: "Billing Option", exact: true });
  await expect(price).toHaveValue("12");
  await price.fill("99");
  await line.getByLabel("Quantity", { exact: true }).fill("2");
  await expect(price).toHaveValue("99");

  await setEditMode(page, true);
  await page.getByRole("button", { name: "Edit Business Basic", exact: true }).click();
  await editor.getByLabel("License name", { exact: true }).fill("Basic Renewed");
  await editor.getByLabel("Monthly price", { exact: true }).fill("11");
  await editor.getByRole("button", { name: "Save changes", exact: true }).click();
  await page.getByRole("button", { name: "Edit product", exact: true }).click();
  const productEditor = page.getByRole("dialog", { name: "Edit product", exact: true });
  await productEditor.getByLabel("Product name", { exact: true }).fill("Microsoft Business");
  await productEditor.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(price).toHaveValue("99");
  await page.reload();
  await expect(page.getByRole("button", { name: "Add Basic Renewed to quote", exact: true })).toBeVisible();
  await expect(line.getByText("Microsoft 365", { exact: true })).toBeVisible();
  await expect(price).toHaveValue("99");
  await expect(line.getByLabel("Quantity", { exact: true })).toHaveValue("2");
  await billing.selectOption("monthly");
  await expect(price).toHaveValue("11");
  await billing.selectOption("annual-upfront");
  await expect(price).toHaveValue("");
  await expect(page.getByRole("button", { name: "Export PDF", exact: true })).toBeDisabled();
  await billing.selectOption("annual-monthly");
  await expect(price).toHaveValue("12");

  await setEditMode(page, true);
  await page.getByRole("button", { name: "Edit Basic Renewed", exact: true }).click();
  page.once("dialog", (dialog) => dialog.accept());
  await editor.getByRole("button", { name: "Delete license", exact: true }).click();
  await expect(price).toHaveValue("12");
  await page.getByRole("button", { name: "Add license", exact: true }).click();
  const replacement = page.getByRole("dialog", { name: "Add license", exact: true });
  await replacement.getByLabel("License name", { exact: true }).fill("Business Basic");
  await replacement.getByLabel("Monthly price", { exact: true }).fill("777");
  await replacement.getByLabel("Annual paid monthly price", { exact: true }).fill("888");
  await replacement.getByRole("button", { name: "Add license", exact: true }).click();
  await setEditMode(page, false);
  await billing.selectOption("monthly");
  await expect(price).toHaveValue("");
  await page.getByRole("button", { name: "Add Business Basic to quote", exact: true }).press("Enter");
  const replacementLine = page.getByRole("group", { name: "Business Basic", exact: true }).last();
  await expect(replacementLine.getByRole("textbox", { name: "Price", exact: true })).toHaveValue("888");
  await page.reload();
  await expect(page.getByTestId("quote-line")).toHaveCount(2);
  await expect(price).toHaveValue("");
  await expect(replacementLine.getByRole("textbox", { name: "Price", exact: true })).toHaveValue("888");
});
